<?php

namespace App\Console\Commands;

use App\Models\Item;
use App\Services\Ecotrade\EcotradeGeminiImageEditor;
use Illuminate\Console\Command;
use RuntimeException;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Throwable;

class FixWatermarkIssueImagesCommand extends Command
{
    protected $signature = 'media:fix-watermark-issues
        {report=storage/app/media-audit/2026-07-04/maikcat_watermark_issues.csv : CSV report generated by the watermark scanner}
        {--dry-run : Filter and report eligible images without Gemini calls or media writes}
        {--limit= : Maximum unique media rows to process}
        {--max-attempts=3 : Maximum Gemini edit/verify attempts per image}
        {--min-pixel-score=0.12 : Minimum scanner pixel score required for a visual watermark issue}
        {--sleep-ms=0 : Milliseconds to sleep after each media row}
        {--max-cost-usd= : Required paid-run cost ceiling}
        {--output-dir=storage/app/media-audit/watermark-fix : Directory where reports and prompt previews are written}
        {--filtered-report= : Optional filtered CSV output path}
        {--result-report= : Optional result CSV output path}';

    protected $description = 'Repair priceable item images listed in a watermark issue CSV using Gemini and replace verified clean media';

    /** @var list<string> */
    private array $reportHeaders = [];

    public function handle(EcotradeGeminiImageEditor $gemini): int
    {
        try {
            $issueReportPath = $this->resolvePath((string) $this->argument('report'));
            $outputDirectory = $this->outputDirectory();
            if (! is_dir($outputDirectory) && ! mkdir($outputDirectory, 0777, true) && ! is_dir($outputDirectory)) {
                throw new RuntimeException('Unable to create output directory: '.$outputDirectory);
            }

            $issueRows = $this->readIssueRows($issueReportPath);
            $mediaById = $this->priceableMediaById($this->mediaIds($issueRows));
            $filteredRows = $this->filteredRows($issueRows, $mediaById);
            $filteredReportPath = $this->filteredReportPath($outputDirectory);
            $resultReportPath = $this->resultReportPath($outputDirectory);
            $promptPath = $outputDirectory.DIRECTORY_SEPARATOR.'watermark_fix_prompt.txt';
            $maxAttempts = max(1, (int) $this->option('max-attempts'));
            $candidates = $this->candidateMedia($issueRows, $mediaById);
            $limit = $this->limit();

            if ($limit !== null) {
                $candidates = array_slice($candidates, 0, $limit, preserve_keys: true);
            }

            $this->writeFilteredReport($filteredReportPath, $filteredRows);
            file_put_contents($promptPath, $this->editPrompt(null, 1));
            $estimatedCalls = count($candidates) * $maxAttempts * 2;
            $estimatedCost = $this->estimatedCost($estimatedCalls);

            $this->printPlan(
                $issueReportPath,
                $filteredReportPath,
                $resultReportPath,
                $promptPath,
                count($issueRows),
                count($filteredRows),
                count($candidates),
                $maxAttempts,
                $estimatedCalls,
                $estimatedCost,
            );

            if ((bool) $this->option('dry-run')) {
                $this->comment('Dry run completed without Gemini calls or media writes.');

                return self::SUCCESS;
            }

            if ($candidates === []) {
                $this->comment('No eligible watermark issue images need fixing.');
                $this->writeResultReport($resultReportPath, []);

                return self::SUCCESS;
            }

            if (! $this->costAllowed($estimatedCost)) {
                return self::FAILURE;
            }

            $resultRows = $this->repairMedia($candidates, $gemini, $maxAttempts);
            $this->writeResultReport($resultReportPath, $resultRows);
            $this->printResultSummary($resultRows);

            return self::SUCCESS;
        } catch (Throwable $exception) {
            $this->error('Watermark issue repair failed: '.$exception->getMessage());

            return self::FAILURE;
        }
    }

    /**
     * @return list<array<string, string>>
     */
    private function readIssueRows(string $path): array
    {
        $handle = fopen($path, 'rb');

        if ($handle === false) {
            throw new RuntimeException('Unable to open watermark issue CSV: '.$path);
        }

        try {
            $header = fgetcsv($handle);

            if (! is_array($header)) {
                throw new RuntimeException('Watermark issue CSV has no header: '.$path);
            }

            $this->reportHeaders = array_map(static fn (mixed $value): string => (string) $value, $header);
            $rows = [];

            while (($values = fgetcsv($handle)) !== false) {
                $row = [];

                foreach ($this->reportHeaders as $index => $name) {
                    $row[$name] = (string) ($values[$index] ?? '');
                }

                $rows[] = $row;
            }

            return $rows;
        } finally {
            fclose($handle);
        }
    }

    /**
     * @param  list<array<string, string>>  $rows
     * @return list<int>
     */
    private function mediaIds(array $rows): array
    {
        $ids = [];

        foreach ($rows as $row) {
            if (is_numeric($row['media_id'] ?? null)) {
                $ids[] = (int) $row['media_id'];
            }
        }

        return array_values(array_unique($ids));
    }

    /**
     * @param  list<int>  $mediaIds
     * @return array<int, Media>
     */
    private function priceableMediaById(array $mediaIds): array
    {
        if ($mediaIds === []) {
            return [];
        }

        return Media::query()
            ->with('model')
            ->whereIn('id', $mediaIds)
            ->where('model_type', Item::class)
            ->where('collection_name', 'images')
            ->get()
            ->filter(fn (Media $media): bool => $this->isPriceableItemMedia($media))
            ->keyBy('id')
            ->all();
    }

    private function isPriceableItemMedia(Media $media): bool
    {
        $item = $media->model;

        return $item instanceof Item
            && (float) $item->weight_kg > 0.0
            && (
                (float) $item->pt_ppm > 0.0
                || (float) $item->pd_ppm > 0.0
                || (float) $item->rh_ppm > 0.0
            )
            && is_file($media->getPath());
    }

    /**
     * @param  list<array<string, string>>  $rows
     * @param  array<int, Media>  $mediaById
     * @return list<array<string, string>>
     */
    private function filteredRows(array $rows, array $mediaById): array
    {
        $filtered = [];

        foreach ($rows as $row) {
            $mediaId = is_numeric($row['media_id'] ?? null) ? (int) $row['media_id'] : null;

            if (
                $mediaId === null
                || ! isset($mediaById[$mediaId])
                || ! $this->isOriginalVisualWatermarkRow($row)
            ) {
                continue;
            }

            $row['priceable_item'] = 'true';
            $filtered[] = $row;
        }

        return $filtered;
    }

    /**
     * @param  list<array<string, string>>  $rows
     * @param  array<int, Media>  $mediaById
     * @return array<int, Media>
     */
    private function candidateMedia(array $rows, array $mediaById): array
    {
        $candidates = [];

        foreach ($rows as $row) {
            if (($row['variant'] ?? '') !== 'original') {
                continue;
            }

            $mediaId = is_numeric($row['media_id'] ?? null) ? (int) $row['media_id'] : null;

            if (
                $mediaId !== null
                && isset($mediaById[$mediaId])
                && $this->isOriginalVisualWatermarkRow($row)
            ) {
                $candidates[$mediaId] = $mediaById[$mediaId];
            }
        }

        return $candidates;
    }

    /**
     * @param  array<string, string>  $row
     */
    private function isOriginalVisualWatermarkRow(array $row): bool
    {
        if (($row['variant'] ?? '') !== 'original') {
            return false;
        }

        if (! str_contains((string) ($row['detection_method'] ?? ''), 'pixel_mask')) {
            return false;
        }

        $pixelScore = is_numeric($row['pixel_score'] ?? null) ? (float) $row['pixel_score'] : 0.0;

        return $pixelScore >= $this->minimumPixelScore();
    }

    private function minimumPixelScore(): float
    {
        $score = $this->option('min-pixel-score');

        return is_numeric($score) ? max(0.0, (float) $score) : 0.12;
    }

    /**
     * @param  array<int, Media>  $candidates
     * @return list<array<string, mixed>>
     */
    private function repairMedia(array $candidates, EcotradeGeminiImageEditor $gemini, int $maxAttempts): array
    {
        $rows = [];
        $sleepMs = max(0, (int) $this->option('sleep-ms'));
        $bar = $this->output->createProgressBar(count($candidates));
        $bar->start();

        foreach ($candidates as $media) {
            $rows[] = $this->repairOneMedia($media, $gemini, $maxAttempts);
            $bar->advance();

            if ($sleepMs > 0) {
                usleep($sleepMs * 1000);
            }
        }

        $bar->finish();
        $this->newLine(2);

        return $rows;
    }

    /**
     * @return array<string, mixed>
     */
    private function repairOneMedia(Media $media, EcotradeGeminiImageEditor $gemini, int $maxAttempts): array
    {
        $sourcePath = $media->getPath();
        $sourceBytes = (string) file_get_contents($sourcePath);
        $sourceMimeType = $this->mimeType($sourcePath, $sourceBytes);
        $lastInspection = null;

        for ($attempt = 1; $attempt <= $maxAttempts; $attempt++) {
            try {
                $edited = $gemini->edit($sourceBytes, $sourceMimeType, $this->editPrompt($lastInspection, $attempt));
                $inspection = $this->inspectGeneratedImage($gemini, $edited['bytes'], $edited['mime_type']);
                $lastInspection = $inspection['notes'];

                if (! $inspection['has_watermark']) {
                    $newMedia = $this->replaceMedia($media, $edited['bytes'], $edited['mime_type'], $attempt, $inspection);

                    return $this->resultRow($media, 'fixed', $attempt, $inspection, $newMedia);
                }
            } catch (Throwable $exception) {
                $lastInspection = $exception->getMessage();

                if ($attempt === $maxAttempts) {
                    return $this->resultRow($media, 'failed', $attempt, [
                        'has_watermark' => true,
                        'terms' => [],
                        'notes' => $exception->getMessage(),
                        'raw' => null,
                    ]);
                }
            }
        }

        return $this->resultRow($media, 'failed_verification', $maxAttempts, [
            'has_watermark' => true,
            'terms' => [],
            'notes' => $lastInspection,
            'raw' => null,
        ]);
    }

    /**
     * @return array{has_watermark: bool, terms: list<string>, notes: string|null, raw: string|null}
     */
    private function inspectGeneratedImage(EcotradeGeminiImageEditor $gemini, string $imageBytes, string $mimeType): array
    {
        $raw = $gemini->inspect($imageBytes, $mimeType, $this->inspectionPrompt());
        $json = $this->decodeJsonObject($raw);

        return [
            'has_watermark' => (bool) ($json['has_watermark'] ?? true),
            'terms' => array_values(array_filter(array_map('strval', (array) ($json['watermark_terms'] ?? [])))),
            'notes' => is_string($json['notes'] ?? null) ? $json['notes'] : null,
            'raw' => $raw,
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function decodeJsonObject(string $raw): array
    {
        $trimmed = trim($raw);
        $trimmed = preg_replace('/^```(?:json)?|```$/m', '', $trimmed) ?? $trimmed;
        $start = strpos($trimmed, '{');
        $end = strrpos($trimmed, '}');

        if ($start !== false && $end !== false && $end >= $start) {
            $trimmed = substr($trimmed, $start, $end - $start + 1);
        }

        $decoded = json_decode($trimmed, true);

        if (! is_array($decoded)) {
            throw new RuntimeException('Gemini inspection did not return parseable JSON: '.$raw);
        }

        return $decoded;
    }

    private function replaceMedia(Media $media, string $bytes, string $mimeType, int $attempts, array $inspection): Media
    {
        $item = $media->model;

        if (! $item instanceof Item) {
            throw new RuntimeException('Media '.$media->id.' does not belong to an item.');
        }

        $extension = $this->extensionForMimeType($mimeType);
        $path = $this->writeTempFile($bytes, $extension);
        $properties = $media->custom_properties ?? [];

        try {
            return $item
                ->addMedia($path)
                ->usingName($media->name ?: pathinfo($media->file_name, PATHINFO_FILENAME))
                ->usingFileName($this->cleanFileName($media->file_name, $extension))
                ->withCustomProperties(array_merge($properties, [
                    'gemini_model' => config('services.gemini.image_model', 'gemini-2.5-flash-image'),
                    'gemini_result' => 'watermark_fixed',
                    'gemini_processed_at' => now()->toISOString(),
                    'gemini_prompt_version' => 'watermark-fix-v1',
                    'watermark_mode' => 'none',
                    'watermark_text' => null,
                    'watermark_asset' => null,
                    'maikcat_watermark' => false,
                    'watermark_fix_source_media_id' => $media->id,
                    'watermark_fix_attempts' => $attempts,
                    'watermark_fix_verification_terms' => $inspection['terms'] ?? [],
                ]))
                ->toMediaCollection('images');
        } finally {
            if (is_file($path)) {
                @unlink($path);
            }
        }
    }

    private function editPrompt(?string $feedback, int $attempt): string
    {
        $attemptInstruction = match ($attempt) {
            1 => 'Remove every visible watermark or supplier mark.',
            2 => 'The previous output may still contain faint watermark remnants. Inspect the whole image carefully and remove remaining fragments.',
            default => 'This is a strict cleanup pass. Focus on tiny partial letters, circular logo pieces, repeated diagonal text, and low-opacity gray/white overlays.',
        };

        $feedbackBlock = $feedback ? "\nPrevious verification feedback:\n{$feedback}\n" : '';

        return trim(<<<PROMPT
Prepare the attached automotive catalytic converter product photo for a clean e-commerce catalog listing.

Goal:
{$attemptInstruction}

Remove all visible text/logo watermarks, supplier marks, copyright notices, source attribution, repeated background marks, and partial watermark fragments. This includes any form of "Maik Cat", "maikcat", "EcoTrade", "ecotrade", circular watermark logos, diagonal overlay text, cropped word pieces, and faint repeated marks.

Preserve the exact physical product:
- Keep the same catalytic converter shape, angle, proportions, holes, flanges, welds, seams, dents, rust, scratches, and metal texture.
- Do not make the item newer, cleaner, polished, redesigned, or repaired.
- Do not invent missing product parts or change the serial/real engraved markings on the metal.
- Keep the same composition, crop, aspect ratio, and plain white/light background.

After removing the watermark, reconstruct only the affected background/product pixels naturally. Do not add any new logos, text, signatures, labels, borders, stickers, or watermarks.
{$feedbackBlock}
Return only the edited image.
PROMPT);
    }

    private function inspectionPrompt(): string
    {
        return trim(<<<'PROMPT'
Inspect the attached product image for visible watermark problems.

Return JSON only, with this exact shape:
{"has_watermark":true,"watermark_terms":["example"],"notes":"short reason"}

Mark has_watermark true if you see any supplier watermark, logo overlay, repeated background text, copyright/source attribution, or partial/faint fragments such as Maik Cat, maikcat, EcoTrade, ecotrade, circular watermark logos, cropped letters, or diagonal overlay marks.
Mark has_watermark false only if the product image is clean from watermark overlays.
Ignore real engraved serial numbers, stamped metal part codes, rust, scratches, shadows, and physical labels that are part of the actual object.
PROMPT);
    }

    /**
     * @return array<string, mixed>
     */
    private function resultRow(Media $media, string $status, int $attempts, array $inspection, ?Media $newMedia = null): array
    {
        $item = $media->model;

        return [
            'status' => $status,
            'old_media_id' => $media->id,
            'new_media_id' => $newMedia?->id,
            'item_id' => $item instanceof Item ? $item->id : $media->model_id,
            'old_file_name' => $media->file_name,
            'new_file_name' => $newMedia?->file_name,
            'old_path' => $media->getPath(),
            'new_path' => $newMedia?->getPath(),
            'attempts' => $attempts,
            'has_watermark_after' => $inspection['has_watermark'] ? 'true' : 'false',
            'watermark_terms' => implode('|', (array) ($inspection['terms'] ?? [])),
            'verification_notes' => $inspection['notes'] ?? null,
            'verification_raw' => $inspection['raw'] ?? null,
        ];
    }

    private function mimeType(string $path, string $bytes): string
    {
        $fileMime = is_file($path) ? mime_content_type($path) : false;

        if (is_string($fileMime) && str_starts_with($fileMime, 'image/')) {
            return $fileMime;
        }

        $bufferMime = finfo_buffer(finfo_open(FILEINFO_MIME_TYPE), $bytes) ?: null;

        return is_string($bufferMime) && str_starts_with($bufferMime, 'image/') ? $bufferMime : 'image/png';
    }

    private function extensionForMimeType(string $mimeType): string
    {
        return match (strtolower($mimeType)) {
            'image/jpeg', 'image/jpg' => 'jpg',
            'image/webp' => 'webp',
            'image/avif' => 'avif',
            default => 'png',
        };
    }

    private function writeTempFile(string $bytes, string $extension): string
    {
        $path = tempnam(sys_get_temp_dir(), 'watermark_fix_');

        if ($path === false) {
            throw new RuntimeException('Unable to allocate temporary image file.');
        }

        $target = $path.'.'.$extension;
        @unlink($path);
        file_put_contents($target, $bytes);

        return $target;
    }

    private function cleanFileName(string $fileName, string $extension): string
    {
        $base = pathinfo($fileName, PATHINFO_FILENAME);
        $base = preg_replace('/(?:^|-)maikcat(?:-|$)/i', '-', $base) ?? $base;
        $base = trim((string) preg_replace('/-+/', '-', $base), '-');

        return ($base !== '' ? $base : 'fixed-product-image').'.'.$extension;
    }

    /**
     * @param  list<array<string, string>>  $rows
     */
    private function writeFilteredReport(string $path, array $rows): void
    {
        $headers = array_values(array_unique(array_merge($this->reportHeaders, ['priceable_item'])));
        $handle = fopen($path, 'wb');

        if ($handle === false) {
            throw new RuntimeException('Unable to write filtered report: '.$path);
        }

        try {
            fputcsv($handle, $headers);

            foreach ($rows as $row) {
                fputcsv($handle, array_map(static fn (string $header): string => $row[$header] ?? '', $headers));
            }
        } finally {
            fclose($handle);
        }
    }

    /**
     * @param  list<array<string, mixed>>  $rows
     */
    private function writeResultReport(string $path, array $rows): void
    {
        $headers = [
            'status',
            'old_media_id',
            'new_media_id',
            'item_id',
            'old_file_name',
            'new_file_name',
            'old_path',
            'new_path',
            'attempts',
            'has_watermark_after',
            'watermark_terms',
            'verification_notes',
            'verification_raw',
        ];
        $handle = fopen($path, 'wb');

        if ($handle === false) {
            throw new RuntimeException('Unable to write result report: '.$path);
        }

        try {
            fputcsv($handle, $headers);

            foreach ($rows as $row) {
                fputcsv($handle, array_map(static fn (string $header): mixed => $row[$header] ?? '', $headers));
            }
        } finally {
            fclose($handle);
        }
    }

    private function outputDirectory(): string
    {
        $directory = $this->resolveOutputPath((string) $this->option('output-dir'));

        return $directory.DIRECTORY_SEPARATOR.now()->format('Y-m-d');
    }

    private function filteredReportPath(string $outputDirectory): string
    {
        $path = $this->option('filtered-report');

        return is_string($path) && trim($path) !== ''
            ? $this->resolveOutputPath($path)
            : $outputDirectory.DIRECTORY_SEPARATOR.'priceable_maikcat_watermark_issues.csv';
    }

    private function resultReportPath(string $outputDirectory): string
    {
        $path = $this->option('result-report');

        return is_string($path) && trim($path) !== ''
            ? $this->resolveOutputPath($path)
            : $outputDirectory.DIRECTORY_SEPARATOR.'watermark_fix_results.csv';
    }

    private function limit(): ?int
    {
        $limit = $this->option('limit');

        return is_numeric($limit) ? max(1, (int) $limit) : null;
    }

    private function costAllowed(float $estimatedCost): bool
    {
        $maxCost = $this->option('max-cost-usd');

        if (! is_numeric($maxCost)) {
            $this->error('Paid run requires --max-cost-usd. Use --dry-run first to review the filtered CSV and estimate.');

            return false;
        }

        if ($estimatedCost > (float) $maxCost) {
            $this->error('Estimated Gemini cost $'.number_format($estimatedCost, 4).' exceeds --max-cost-usd=$'.number_format((float) $maxCost, 4).'.');

            return false;
        }

        return true;
    }

    private function estimatedCost(int $callCount): float
    {
        return round($callCount * (float) config('services.gemini.image_cost_usd', 0.039387), 6);
    }

    private function printPlan(
        string $issueReport,
        string $filteredReport,
        string $resultReport,
        string $promptPath,
        int $issueRows,
        int $filteredRows,
        int $candidateCount,
        int $maxAttempts,
        int $estimatedCalls,
        float $estimatedCost,
    ): void {
        $this->newLine();
        $this->line('Watermark Issue Gemini Repair');
        $this->line('Issue report: '.$issueReport);
        $this->line('Filtered priceable report: '.$filteredReport);
        $this->line('Result report: '.$resultReport);
        $this->line('Prompt preview: '.$promptPath);
        $this->line('Issue CSV rows: '.$issueRows);
        $this->line('Priceable original visual watermark rows: '.$filteredRows);
        $this->line('Unique original media candidates: '.$candidateCount);
        $this->line('Minimum pixel score: '.$this->minimumPixelScore());
        $this->line('Max attempts per image: '.$maxAttempts);
        $this->line('Estimated Gemini calls: '.$estimatedCalls);
        $this->line('Estimated Gemini cost usd: $'.number_format($estimatedCost, 4));
        $this->newLine();
    }

    /**
     * @param  list<array<string, mixed>>  $rows
     */
    private function printResultSummary(array $rows): void
    {
        $counts = array_count_values(array_map(static fn (array $row): string => (string) $row['status'], $rows));

        $this->line('Watermark repair completed.');
        $this->line('- Fixed: '.(int) ($counts['fixed'] ?? 0));
        $this->line('- Failed verification: '.(int) ($counts['failed_verification'] ?? 0));
        $this->line('- Failed: '.(int) ($counts['failed'] ?? 0));
    }

    private function resolvePath(string $path): string
    {
        if (is_file($path)) {
            return $path;
        }

        $candidates = [
            base_path($path),
            storage_path($path),
        ];

        foreach ($candidates as $candidate) {
            if (is_file($candidate)) {
                return $candidate;
            }
        }

        throw new RuntimeException('File not found: '.$path);
    }

    private function resolveOutputPath(string $path): string
    {
        $path = trim($path);

        if ((bool) preg_match('/^[A-Za-z]:[\\\\\\/]/', $path) || str_starts_with($path, '/') || str_starts_with($path, '\\')) {
            return $path;
        }

        return base_path($path);
    }
}
