<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Models\CarGroup;
use App\Models\Item;
use App\Services\Ecotrade\EcotradeImageReferenceIndex;
use App\Services\Ecotrade\EcotradeJsonReader;
use Illuminate\Console\Command;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use InvalidArgumentException;
use RuntimeException;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Throwable;

final class RemediateItemGroupMappingCommand extends Command
{
    private const string TARGET_STATUS = 'group_mapping_conflict';

    private const array OUTPUT_HEADERS = [
        'status',
        'resolution',
        'reason',
        'item_id',
        'serial_code',
        'normalized_serial',
        'current_car_group_id',
        'current_car_group',
        'proposed_car_group_id',
        'proposed_car_group',
        'current_item_source_url',
        'current_item_source_hash',
        'proposed_item_source_url',
        'proposed_item_source_hash',
        'media_id',
        'media_file_name',
        'media_source_url',
        'media_source_hash',
        'resolved_reference_serial',
        'resolved_reference_product_url',
        'resolved_reference_source_hash',
        'match_method',
        'reference_count',
        'serial_match',
        'group_change_required',
        'source_backfill_required',
        'applied',
    ];

    protected $signature = 'media:remediate-item-group-mapping
        {report : Path to image_link_audit.csv generated by media:audit-item-image-links}
        {json=ecotrade_products_all.json : Path to the Ecotrade JSON source}
        {--apply : Apply only safe, unambiguous identity corrections. Without this option the command is a dry run}
        {--output= : Output directory; defaults to a timestamped directory under storage/app/reports}
        {--code=* : Restrict rows to one or more serial codes}
        {--limit= : Maximum number of group_mapping_conflict rows to evaluate}';

    protected $description = 'Safely resolve group_mapping_conflict rows by authoritative media provenance without changing any images';

    public function handle(
        EcotradeJsonReader $jsonReader,
        EcotradeImageReferenceIndex $referenceIndex,
    ): int {
        try {
            $reportPath = $this->resolvePath((string) $this->argument('report'));
            $outputDirectory = $this->outputDirectory();
            $this->createOutputDirectory($outputDirectory);

            $referenceIndex->build($jsonReader->readIterator((string) $this->argument('json')));
            $rows = $this->targetRows($this->readReport($reportPath));
            $items = $this->loadItems($rows);
            $groups = CarGroup::query()->get(['id', 'name', 'excel_sheet_name'])->keyBy(fn (CarGroup $group): string => (string) $group->getKey());

            $plan = [];
            $unsolved = [];
            $applied = [];
            $alreadyResolved = 0;

            foreach ($rows as $row) {
                $item = $items->get((string) ($row['item_id'] ?? ''));

                if (! $item instanceof Item) {
                    $unsolved[] = $this->outputRow(
                        $row,
                        resolution: 'unsolved',
                        reason: 'target_item_missing',
                    );
                    continue;
                }

                if ($this->isNoLongerAConflict($item, $referenceIndex)) {
                    $alreadyResolved++;
                    continue;
                }

                $decision = $this->decisionFor($item, $row, $referenceIndex, $groups);

                if (! $decision['safe']) {
                    $unsolved[] = $this->outputRow(
                        $row,
                        resolution: 'unsolved',
                        reason: $decision['reason'],
                        item: $item,
                        decision: $decision,
                    );
                    continue;
                }

                $planRow = $this->outputRow(
                    $row,
                    resolution: 'repairable',
                    reason: 'authoritative_media_provenance_matches_item_serial',
                    item: $item,
                    decision: $decision,
                );
                $plan[] = $planRow;

                if (! (bool) $this->option('apply')) {
                    continue;
                }

                try {
                    $updated = $this->applyDecision($item, $decision);
                    $appliedRow = $planRow;
                    $appliedRow['resolution'] = 'applied';
                    $appliedRow['reason'] = 'group_and_source_identity_corrected';
                    $appliedRow['applied'] = 'yes';
                    $appliedRow['current_car_group_id'] = (string) $updated->car_group_id;
                    $appliedRow['current_item_source_url'] = (string) ($updated->source_url ?? '');
                    $appliedRow['current_item_source_hash'] = (string) ($updated->source_hash ?? '');
                    $applied[] = $appliedRow;
                } catch (Throwable $exception) {
                    $unsolved[] = $this->outputRow(
                        $row,
                        resolution: 'unsolved',
                        reason: 'apply_failed: '.$exception->getMessage(),
                        item: $item,
                        decision: $decision,
                    );
                }
            }

            $this->writeCsv($outputDirectory.'/identity_remediation_plan.csv', $plan);
            $this->writeCsv($outputDirectory.'/identity_remediation_applied.csv', $applied);
            $this->writeCsv($outputDirectory.'/identity_remediation_unsolved.csv', $unsolved);
            $this->writeSummary($outputDirectory, [
                'report' => $reportPath,
                'json' => (string) $this->argument('json'),
                'apply' => (bool) $this->option('apply'),
                'target_group_mapping_conflicts' => count($rows),
                'already_resolved' => $alreadyResolved,
                'repairable' => count($plan),
                'applied' => count($applied),
                'unsolved' => count($unsolved),
            ]);

            $this->info((bool) $this->option('apply')
                ? 'Group mapping identity remediation completed.'
                : 'Group mapping identity remediation dry run completed without database changes.');
            $this->line('Group mapping conflicts evaluated: '.count($rows));
            $this->line('Already resolved since report: '.$alreadyResolved);
            $this->line('Safe identity corrections: '.count($plan));
            $this->line('Corrections applied: '.count($applied));
            $this->line('Still unresolved: '.count($unsolved));
            $this->line('Reports: '.$outputDirectory);

            if (! (bool) $this->option('apply') && $plan !== []) {
                $this->comment('Review identity_remediation_plan.csv, then rerun the same command with --apply.');
            }

            return self::SUCCESS;
        } catch (Throwable $exception) {
            $this->error('Group mapping identity remediation failed: '.$exception->getMessage());

            return self::FAILURE;
        }
    }

    /** @return array{safe:bool,reason:string,reference:array<string,mixed>|null,group_id:string,group_name:string,source_hash:string,product_url:string,match_method:string,serial_match:bool,group_change:bool,source_backfill:bool} */
    private function decisionFor(
        Item $item,
        array $row,
        EcotradeImageReferenceIndex $referenceIndex,
        Collection $groups,
    ): array {
        $empty = [
            'safe' => false,
            'reason' => '',
            'reference' => null,
            'group_id' => '',
            'group_name' => '',
            'source_hash' => '',
            'product_url' => '',
            'match_method' => '',
            'serial_match' => false,
            'group_change' => false,
            'source_backfill' => false,
        ];

        $media = $item->getFirstMedia('images');

        if (! $media instanceof Media || ! is_file($media->getPath())) {
            return [...$empty, 'reason' => 'current_media_unavailable'];
        }

        [$references, $matchMethod] = $this->resolveMediaReferences($media, $referenceIndex);

        if ($references === []) {
            return [...$empty, 'reason' => 'media_provenance_not_found_in_json'];
        }

        if (count($references) !== 1) {
            return [...$empty, 'reason' => 'media_provenance_resolves_to_multiple_json_products'];
        }

        $reference = $references[0];
        $normalizedSerial = Item::normalizeSerialValue($item->normalized_serial ?: $item->serial_code);
        $matchingGroupIds = $this->matchingGroupIds($reference, $normalizedSerial);

        if ($normalizedSerial === '' || $matchingGroupIds === []) {
            return [
                ...$empty,
                'reason' => 'media_product_serial_does_not_match_item_serial',
                'reference' => $reference,
                'match_method' => $matchMethod,
            ];
        }

        if (count($matchingGroupIds) !== 1) {
            return [
                ...$empty,
                'reason' => 'media_product_maps_to_multiple_groups_for_item_serial',
                'reference' => $reference,
                'match_method' => $matchMethod,
                'serial_match' => true,
            ];
        }

        $groupId = $matchingGroupIds[0];
        $group = $groups->get($groupId);

        if (! $group instanceof CarGroup) {
            return [
                ...$empty,
                'reason' => 'resolved_group_missing_from_database',
                'reference' => $reference,
                'group_id' => $groupId,
                'match_method' => $matchMethod,
                'serial_match' => true,
            ];
        }

        $sourceHash = trim((string) ($reference['source_hash'] ?? ''));
        $productUrl = trim((string) ($reference['product_url'] ?? ''));

        if ($sourceHash === '' || $productUrl === '') {
            return [
                ...$empty,
                'reason' => 'resolved_json_product_has_incomplete_identity',
                'reference' => $reference,
                'group_id' => $groupId,
                'group_name' => (string) $group->name,
                'match_method' => $matchMethod,
                'serial_match' => true,
            ];
        }

        $existingHash = trim((string) ($item->source_hash ?? ''));
        $existingUrl = $this->normalizeUrl((string) ($item->source_url ?? ''));

        if ($existingHash !== '' && ! hash_equals($existingHash, $sourceHash)) {
            return [
                ...$empty,
                'reason' => 'existing_item_source_hash_conflicts_with_media_product',
                'reference' => $reference,
                'group_id' => $groupId,
                'group_name' => (string) $group->name,
                'source_hash' => $sourceHash,
                'product_url' => $productUrl,
                'match_method' => $matchMethod,
                'serial_match' => true,
            ];
        }

        if ($existingUrl !== '' && $existingUrl !== $this->normalizeUrl($productUrl)) {
            return [
                ...$empty,
                'reason' => 'existing_item_source_url_conflicts_with_media_product',
                'reference' => $reference,
                'group_id' => $groupId,
                'group_name' => (string) $group->name,
                'source_hash' => $sourceHash,
                'product_url' => $productUrl,
                'match_method' => $matchMethod,
                'serial_match' => true,
            ];
        }

        $mediaHash = trim((string) $media->getCustomProperty('source_hash'));

        if ($matchMethod === 'source_hash' && ($mediaHash === '' || ! hash_equals($mediaHash, $sourceHash))) {
            return [
                ...$empty,
                'reason' => 'media_source_hash_does_not_equal_resolved_product_hash',
                'reference' => $reference,
                'group_id' => $groupId,
                'group_name' => (string) $group->name,
                'source_hash' => $sourceHash,
                'product_url' => $productUrl,
                'match_method' => $matchMethod,
                'serial_match' => true,
            ];
        }

        $groupChange = (string) $item->car_group_id !== $groupId;
        $sourceBackfill = $existingHash === '' || $existingUrl === '';

        if (! $groupChange && ! $sourceBackfill) {
            return [
                ...$empty,
                'reason' => 'item_identity_already_matches_resolved_product',
                'reference' => $reference,
                'group_id' => $groupId,
                'group_name' => (string) $group->name,
                'source_hash' => $sourceHash,
                'product_url' => $productUrl,
                'match_method' => $matchMethod,
                'serial_match' => true,
            ];
        }

        return [
            'safe' => true,
            'reason' => 'safe',
            'reference' => $reference,
            'group_id' => $groupId,
            'group_name' => (string) $group->name,
            'source_hash' => $sourceHash,
            'product_url' => $productUrl,
            'match_method' => $matchMethod,
            'serial_match' => true,
            'group_change' => $groupChange,
            'source_backfill' => $sourceBackfill,
        ];
    }

    /** @return array{0:list<array<string,mixed>>,1:string} */
    private function resolveMediaReferences(Media $media, EcotradeImageReferenceIndex $referenceIndex): array
    {
        $sourceHash = trim((string) $media->getCustomProperty('source_hash'));

        if ($sourceHash !== '') {
            $references = $this->uniqueReferences($referenceIndex->referencesForSourceHash($sourceHash));

            if ($references !== []) {
                return [$references, 'media_source_hash'];
            }
        }

        $sourceUrl = trim((string) $media->getCustomProperty('source_url'));

        if ($sourceUrl !== '') {
            $references = $this->uniqueReferences($referenceIndex->referencesForSourceUrl($sourceUrl));

            if ($references !== []) {
                return [$references, 'media_source_url'];
            }
        }

        return [[], ''];
    }

    /** @param list<array<string,mixed>> $references @return list<array<string,mixed>> */
    private function uniqueReferences(array $references): array
    {
        $unique = [];

        foreach ($references as $reference) {
            $hash = trim((string) ($reference['source_hash'] ?? ''));
            $url = $this->normalizeUrl((string) ($reference['product_url'] ?? ''));
            $key = $hash !== '' ? 'hash:'.$hash : 'url:'.$url;
            $unique[$key] = $reference;
        }

        return array_values($unique);
    }

    /** @param array<string,mixed> $reference @return list<string> */
    private function matchingGroupIds(array $reference, string $normalizedSerial): array
    {
        $groups = [];

        foreach ((array) ($reference['family_keys'] ?? []) as $familyKey) {
            if (! is_string($familyKey) || ! str_contains($familyKey, '|')) {
                continue;
            }

            [$groupId, $serial] = explode('|', $familyKey, 2);

            if ($groupId !== '' && Item::normalizeSerialValue($serial) === $normalizedSerial) {
                $groups[] = $groupId;
            }
        }

        if ($groups === [] && Item::normalizeSerialValue($reference['serial_code'] ?? null) === $normalizedSerial) {
            foreach ((array) ($reference['family_keys'] ?? []) as $familyKey) {
                if (is_string($familyKey) && str_contains($familyKey, '|')) {
                    [$groupId] = explode('|', $familyKey, 2);
                    if ($groupId !== '') {
                        $groups[] = $groupId;
                    }
                }
            }
        }

        return array_values(array_unique($groups));
    }

    /** @param array{safe:bool,reason:string,reference:array<string,mixed>|null,group_id:string,group_name:string,source_hash:string,product_url:string,match_method:string,serial_match:bool,group_change:bool,source_backfill:bool} $decision */
    private function applyDecision(Item $item, array $decision): Item
    {
        return DB::transaction(function () use ($item, $decision): Item {
            $locked = Item::query()->lockForUpdate()->find($item->getKey());

            if (! $locked instanceof Item) {
                throw new RuntimeException('Target item disappeared before update.');
            }

            $locked->car_group_id = $decision['group_id'];
            $locked->source = $locked->source ?: 'ecotrade';
            $locked->source_url = $decision['product_url'];
            $locked->source_hash = $decision['source_hash'];
            $locked->save();

            return $locked->fresh(['carGroup', 'media']);
        });
    }

    private function isNoLongerAConflict(Item $item, EcotradeImageReferenceIndex $referenceIndex): bool
    {
        $match = $referenceIndex->referencesFor($item);

        if (($match['ambiguous'] ?? false) === true) {
            return false;
        }

        return count((array) ($match['references'] ?? [])) === 1
            && $this->mediaMatchesReference($item->getFirstMedia('images'), $match['references'][0], $referenceIndex);
    }

    private function mediaMatchesReference(?Media $media, array $reference, EcotradeImageReferenceIndex $referenceIndex): bool
    {
        if (! $media instanceof Media || ! is_file($media->getPath())) {
            return false;
        }

        $sourceHash = trim((string) $media->getCustomProperty('source_hash'));
        $expectedHash = trim((string) ($reference['source_hash'] ?? ''));

        if ($sourceHash !== '' && $expectedHash !== '' && hash_equals($sourceHash, $expectedHash)) {
            return true;
        }

        $sourceUrl = trim((string) $media->getCustomProperty('source_url'));

        if ($sourceUrl === '') {
            return false;
        }

        foreach ($referenceIndex->referencesForSourceUrl($sourceUrl) as $resolved) {
            $resolvedHash = trim((string) ($resolved['source_hash'] ?? ''));
            if ($expectedHash !== '' && $resolvedHash !== '' && hash_equals($expectedHash, $resolvedHash)) {
                return true;
            }
        }

        return false;
    }

    /** @return list<array<string,string>> */
    private function readReport(string $path): array
    {
        if (! is_file($path)) {
            throw new RuntimeException('Audit CSV does not exist: '.$path);
        }

        $handle = fopen($path, 'rb');

        if ($handle === false) {
            throw new RuntimeException('Unable to open audit CSV: '.$path);
        }

        try {
            $headers = fgetcsv($handle);

            if (! is_array($headers) || $headers === []) {
                throw new RuntimeException('Audit CSV has no header row.');
            }

            $headers = array_map(static fn (mixed $value): string => (string) $value, $headers);
            $required = ['status', 'item_id', 'serial_code', 'normalized_serial', 'car_group', 'media_id', 'media_source_url', 'media_source_hash'];

            foreach ($required as $requiredHeader) {
                if (! in_array($requiredHeader, $headers, true)) {
                    throw new RuntimeException('Audit CSV is missing required column: '.$requiredHeader);
                }
            }

            $rows = [];

            while (($values = fgetcsv($handle)) !== false) {
                $row = [];

                foreach ($headers as $index => $header) {
                    $row[$header] = (string) ($values[$index] ?? '');
                }

                $rows[] = $row;
            }

            return $rows;
        } finally {
            fclose($handle);
        }
    }

    /** @param list<array<string,string>> $rows @return list<array<string,string>> */
    private function targetRows(array $rows): array
    {
        $codes = $this->normalizedCodes();
        $target = array_values(array_filter($rows, static function (array $row) use ($codes): bool {
            if (($row['status'] ?? '') !== self::TARGET_STATUS) {
                return false;
            }

            if ($codes === []) {
                return true;
            }

            return in_array(
                Item::normalizeSerialValue(($row['normalized_serial'] ?? '') ?: ($row['serial_code'] ?? '')),
                $codes,
                true,
            );
        }));
        $limit = $this->limit();

        return $limit === null ? $target : array_slice($target, 0, $limit);
    }

    /** @param list<array<string,string>> $rows */
    private function loadItems(array $rows): Collection
    {
        $ids = collect($rows)->pluck('item_id')->filter()->unique()->values()->all();

        if ($ids === []) {
            return collect();
        }

        return Item::query()
            ->with(['media', 'carGroup:id,name,excel_sheet_name'])
            ->whereIn('id', $ids)
            ->get()
            ->keyBy(fn (Item $item): string => (string) $item->getKey());
    }

    /** @param array{safe:bool,reason:string,reference:array<string,mixed>|null,group_id:string,group_name:string,source_hash:string,product_url:string,match_method:string,serial_match:bool,group_change:bool,source_backfill:bool}|null $decision @return array<string,string> */
    private function outputRow(
        array $row,
        string $resolution,
        string $reason,
        ?Item $item = null,
        ?array $decision = null,
    ): array {
        $media = $item?->getFirstMedia('images');
        $reference = $decision['reference'] ?? null;

        return [
            'status' => (string) ($row['status'] ?? self::TARGET_STATUS),
            'resolution' => $resolution,
            'reason' => $reason,
            'item_id' => (string) ($item?->getKey() ?? $row['item_id'] ?? ''),
            'serial_code' => (string) ($item?->serial_code ?? $row['serial_code'] ?? ''),
            'normalized_serial' => Item::normalizeSerialValue($item?->normalized_serial ?: ($item?->serial_code ?? $row['normalized_serial'] ?? $row['serial_code'] ?? '')),
            'current_car_group_id' => (string) ($item?->car_group_id ?? $row['car_group_id'] ?? ''),
            'current_car_group' => (string) ($item?->carGroup?->name ?? $row['car_group'] ?? ''),
            'proposed_car_group_id' => (string) ($decision['group_id'] ?? ''),
            'proposed_car_group' => (string) ($decision['group_name'] ?? ''),
            'current_item_source_url' => (string) ($item?->source_url ?? $row['item_source_url'] ?? ''),
            'current_item_source_hash' => (string) ($item?->source_hash ?? $row['item_source_hash'] ?? ''),
            'proposed_item_source_url' => (string) ($decision['product_url'] ?? ''),
            'proposed_item_source_hash' => (string) ($decision['source_hash'] ?? ''),
            'media_id' => (string) ($media?->getKey() ?? $row['media_id'] ?? ''),
            'media_file_name' => (string) ($media?->file_name ?? $row['media_file_name'] ?? ''),
            'media_source_url' => (string) ($media?->getCustomProperty('source_url') ?? $row['media_source_url'] ?? ''),
            'media_source_hash' => (string) ($media?->getCustomProperty('source_hash') ?? $row['media_source_hash'] ?? ''),
            'resolved_reference_serial' => is_array($reference) ? (string) ($reference['serial_code'] ?? '') : '',
            'resolved_reference_product_url' => is_array($reference) ? (string) ($reference['product_url'] ?? '') : '',
            'resolved_reference_source_hash' => is_array($reference) ? (string) ($reference['source_hash'] ?? '') : '',
            'match_method' => (string) ($decision['match_method'] ?? ''),
            'reference_count' => is_array($reference) ? '1' : '',
            'serial_match' => ($decision['serial_match'] ?? false) ? 'yes' : 'no',
            'group_change_required' => ($decision['group_change'] ?? false) ? 'yes' : 'no',
            'source_backfill_required' => ($decision['source_backfill'] ?? false) ? 'yes' : 'no',
            'applied' => 'no',
        ];
    }

    /** @param list<array<string,string>> $rows */
    private function writeCsv(string $path, array $rows): void
    {
        $handle = fopen($path, 'wb');

        if ($handle === false) {
            throw new RuntimeException('Unable to create CSV: '.$path);
        }

        try {
            fputcsv($handle, self::OUTPUT_HEADERS);
            foreach ($rows as $row) {
                fputcsv($handle, array_map(static fn (string $header): string => (string) ($row[$header] ?? ''), self::OUTPUT_HEADERS));
            }
        } finally {
            fclose($handle);
        }
    }

    /** @param array<string,mixed> $summary */
    private function writeSummary(string $outputDirectory, array $summary): void
    {
        $written = file_put_contents(
            $outputDirectory.'/summary.json',
            json_encode($summary, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR),
        );

        if ($written === false) {
            throw new RuntimeException('Unable to write identity remediation summary.');
        }
    }

    /** @return list<string> */
    private function normalizedCodes(): array
    {
        return collect((array) $this->option('code'))
            ->map(static fn (mixed $code): string => Item::normalizeSerialValue($code))
            ->filter()
            ->unique()
            ->values()
            ->all();
    }

    private function limit(): ?int
    {
        $value = $this->option('limit');
        if ($value === null || $value === '') {
            return null;
        }

        $limit = filter_var($value, FILTER_VALIDATE_INT);
        if ($limit === false || $limit < 1) {
            throw new InvalidArgumentException('--limit must be a positive integer.');
        }

        return $limit;
    }

    private function outputDirectory(): string
    {
        $configured = trim((string) $this->option('output'));
        if ($configured === '') {
            return storage_path('app/reports/item-group-mapping-remediation/'.now()->format('Ymd-His'));
        }

        return $this->resolvePath($configured, false);
    }

    private function createOutputDirectory(string $path): void
    {
        if (! is_dir($path) && ! mkdir($path, 0775, true) && ! is_dir($path)) {
            throw new RuntimeException('Unable to create output directory: '.$path);
        }
    }

    private function resolvePath(string $path, bool $mustExist = true): string
    {
        $path = trim($path);
        if ($path === '') {
            throw new InvalidArgumentException('A non-empty path is required.');
        }

        $resolved = (Str::startsWith($path, ['/', '\\']) || preg_match('/^[A-Za-z]:[\\\\\/]/', $path) === 1)
            ? rtrim($path, '\\/')
            : rtrim(base_path($path), '\\/');

        if ($mustExist && ! is_file($resolved)) {
            throw new RuntimeException('File does not exist: '.$resolved);
        }

        return $resolved;
    }

    private function normalizeUrl(string $url): string
    {
        return Str::lower(trim($url));
    }
}
