<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Models\Item;
use Illuminate\Console\Command;
use Illuminate\Support\Str;
use InvalidArgumentException;
use RuntimeException;
use Throwable;

final class SafeRepairItemImageLinksCommand extends Command
{
    private const array OUTPUT_HEADERS = [
        'status',
        'resolution',
        'reason',
        'item_id',
        'car_group',
        'serial_code',
        'normalized_serial',
        'item_source_url',
        'item_source_hash',
        'current_media_id',
        'current_media_file_name',
        'current_media_source_url',
        'current_media_source_hash',
        'expected_product_url',
        'expected_source_hash',
        'target_source_url',
        'target_source_hash',
        'match_method',
        'donor_item_id',
        'donor_media_id',
        'donor_media_file_name',
        'donor_media_source_url',
        'donor_media_source_hash',
        'donor_image_url',
        'result_media_id',
    ];

    protected $signature = 'media:repair-item-image-links-safe
        {report : Path to image_link_audit.csv generated by media:audit-item-image-links}
        {--apply : Replace repairable images. Without this option the command is a dry run}
        {--output= : Output directory; defaults to a timestamped directory under storage/app/reports}
        {--code=* : Restrict target rows to one or more normalized serial codes}
        {--limit= : Maximum number of target rows to evaluate}
        {--include-visual-review-donors : Allow provenance_match_visual_review rows to act as donors}';

    protected $description = 'Safely repair item image links from existing project media while excluding suspicious cross-code image reuse';

    public function handle(): int
    {
        try {
            $reportPath = $this->resolvePath((string) $this->argument('report'));
            $outputDirectory = $this->outputDirectory();
            $this->createOutputDirectory($outputDirectory);

            [$headers, $rows] = $this->readReport($reportPath);
            $crossCodeHashes = $this->crossCodeHashes($rows);
            $derivedReport = $outputDirectory.'/repair_input_cross_code_safe.csv';
            $this->writeDerivedReport($derivedReport, $headers, $rows, $crossCodeHashes);

            $arguments = [
                'report' => $derivedReport,
                '--output' => $outputDirectory,
            ];

            if ((bool) $this->option('apply')) {
                $arguments['--apply'] = true;
            }

            $codes = array_values(array_filter(array_map('strval', (array) $this->option('code'))));

            if ($codes !== []) {
                $arguments['--code'] = $codes;
            }

            $limit = $this->option('limit');

            if ($limit !== null && $limit !== '') {
                $arguments['--limit'] = (string) $limit;
            }

            if ((bool) $this->option('include-visual-review-donors')) {
                $arguments['--include-visual-review-donors'] = true;
            }

            $exitCode = $this->call('media:repair-item-image-links', $arguments);

            if ($exitCode !== self::SUCCESS) {
                return $exitCode;
            }

            $selectedRows = $this->selectedRows($rows);
            $crossCodeRows = array_values(array_filter(
                $selectedRows,
                static fn (array $row): bool => isset($crossCodeHashes[(string) ($row['media_sha256'] ?? '')]),
            ));
            $appended = $this->appendCrossCodeReviewRows($outputDirectory, $crossCodeRows);
            $this->updateSummary($outputDirectory, count($crossCodeHashes), $appended);

            $this->line('Suspicious cross-code image hashes: '.count($crossCodeHashes));
            $this->line('Cross-code rows added to unsolved review: '.$appended);

            return self::SUCCESS;
        } catch (Throwable $exception) {
            $this->error('Safe existing-project image repair failed: '.$exception->getMessage());

            return self::FAILURE;
        }
    }

    /** @return array{0:list<string>,1:list<array<string,string>>} */
    private function readReport(string $path): array
    {
        if (! is_file($path)) {
            throw new RuntimeException('Audit CSV does not exist: '.$path);
        }

        $handle = fopen($path, 'rb');

        if ($handle === false) {
            throw new RuntimeException('Unable to open audit CSV: '.$path);
        }

        try {
            $headers = fgetcsv($handle);

            if (! is_array($headers) || $headers === []) {
                throw new RuntimeException('Audit CSV has no header row.');
            }

            $headers = array_map(static fn (mixed $value): string => (string) $value, $headers);
            $required = [
                'status',
                'item_id',
                'serial_code',
                'normalized_serial',
                'primary_family_key',
                'media_sha256',
                'expected_source_hash',
                'expected_image_url',
            ];

            foreach ($required as $requiredHeader) {
                if (! in_array($requiredHeader, $headers, true)) {
                    throw new RuntimeException('Audit CSV is missing required column: '.$requiredHeader);
                }
            }

            $rows = [];

            while (($values = fgetcsv($handle)) !== false) {
                $row = [];

                foreach ($headers as $index => $header) {
                    $row[$header] = (string) ($values[$index] ?? '');
                }

                $rows[] = $row;
            }

            return [$headers, $rows];
        } finally {
            fclose($handle);
        }
    }

    /** @param list<array<string,string>> $rows @return array<string,true> */
    private function crossCodeHashes(array $rows): array
    {
        $usage = [];

        foreach ($rows as $row) {
            $hash = trim((string) ($row['media_sha256'] ?? ''));
            $familyKey = trim((string) ($row['primary_family_key'] ?? ''));

            if ($hash === '' || $familyKey === '') {
                continue;
            }

            $usage[$hash][$familyKey][] = $row;
        }

        $crossCodeHashes = [];

        foreach ($usage as $hash => $families) {
            if (count($families) < 2 || $this->familiesShareOneReference($families)) {
                continue;
            }

            $crossCodeHashes[$hash] = true;
        }

        return $crossCodeHashes;
    }

    /** @param array<string,list<array<string,string>>> $families */
    private function familiesShareOneReference(array $families): bool
    {
        $sourceHashes = [];
        $imageUrls = [];

        foreach ($families as $rows) {
            foreach ($rows as $row) {
                $sourceHashes[] = trim((string) ($row['expected_source_hash'] ?? ''));
                $imageUrls[] = Str::lower(trim((string) ($row['expected_image_url'] ?? '')));
            }
        }

        $sourceHashes = array_values(array_unique($sourceHashes));
        $imageUrls = array_values(array_unique($imageUrls));

        return (count($sourceHashes) === 1 && $sourceHashes[0] !== '')
            || (count($imageUrls) === 1 && $imageUrls[0] !== '');
    }

    /** @param list<string> $headers @param list<array<string,string>> $rows @param array<string,true> $crossCodeHashes */
    private function writeDerivedReport(string $path, array $headers, array $rows, array $crossCodeHashes): void
    {
        $handle = fopen($path, 'wb');

        if ($handle === false) {
            throw new RuntimeException('Unable to create cross-code-safe repair input: '.$path);
        }

        try {
            fputcsv($handle, $headers);

            foreach ($rows as $row) {
                $hash = (string) ($row['media_sha256'] ?? '');

                if (isset($crossCodeHashes[$hash])) {
                    $row['status'] = 'cross_code_image_reuse';
                }

                fputcsv($handle, array_map(
                    static fn (string $header): string => (string) ($row[$header] ?? ''),
                    $headers,
                ));
            }
        } finally {
            fclose($handle);
        }
    }

    /** @param list<array<string,string>> $rows @return list<array<string,string>> */
    private function selectedRows(array $rows): array
    {
        $codes = collect((array) $this->option('code'))
            ->map(static fn (mixed $code): string => Item::normalizeSerialValue($code))
            ->filter()
            ->unique()
            ->values()
            ->all();

        $selected = array_values(array_filter($rows, static function (array $row) use ($codes): bool {
            if ($codes === []) {
                return true;
            }

            return in_array(
                Item::normalizeSerialValue(($row['normalized_serial'] ?? '') ?: ($row['serial_code'] ?? '')),
                $codes,
                true,
            );
        }));

        $limit = $this->validatedLimit();

        return $limit === null ? $selected : array_slice($selected, 0, $limit);
    }

    /** @param list<array<string,string>> $crossCodeRows */
    private function appendCrossCodeReviewRows(string $outputDirectory, array $crossCodeRows): int
    {
        if ($crossCodeRows === []) {
            $this->writeCrossCodeCsv($outputDirectory.'/cross_code_review.csv', []);

            return 0;
        }

        $unsolvedPath = $outputDirectory.'/unsolved_images.csv';
        $existingItemIds = $this->existingOutputItemIds($unsolvedPath);
        $rows = [];

        foreach ($crossCodeRows as $row) {
            $itemId = (string) ($row['item_id'] ?? '');

            if ($itemId === '' || isset($existingItemIds[$itemId])) {
                continue;
            }

            $rows[] = $this->crossCodeOutputRow($row);
            $existingItemIds[$itemId] = true;
        }

        $this->appendOutputRows($unsolvedPath, $rows);
        $this->writeCrossCodeCsv($outputDirectory.'/cross_code_review.csv', $rows);

        return count($rows);
    }

    /** @return array<string,true> */
    private function existingOutputItemIds(string $path): array
    {
        if (! is_file($path)) {
            return [];
        }

        $handle = fopen($path, 'rb');

        if ($handle === false) {
            return [];
        }

        try {
            $headers = fgetcsv($handle);

            if (! is_array($headers)) {
                return [];
            }

            $itemIdIndex = array_search('item_id', $headers, true);

            if ($itemIdIndex === false) {
                return [];
            }

            $ids = [];

            while (($values = fgetcsv($handle)) !== false) {
                $itemId = (string) ($values[$itemIdIndex] ?? '');

                if ($itemId !== '') {
                    $ids[$itemId] = true;
                }
            }

            return $ids;
        } finally {
            fclose($handle);
        }
    }

    /** @return array<string,string> */
    private function crossCodeOutputRow(array $row): array
    {
        return [
            'status' => 'cross_code_image_reuse',
            'resolution' => 'unsolved',
            'reason' => 'cross_code_image_reuse_requires_review: Identical image bytes are used by different product families; no automatic replacement is safe.',
            'item_id' => (string) ($row['item_id'] ?? ''),
            'car_group' => (string) ($row['car_group'] ?? ''),
            'serial_code' => (string) ($row['serial_code'] ?? ''),
            'normalized_serial' => (string) ($row['normalized_serial'] ?? ''),
            'item_source_url' => (string) ($row['item_source_url'] ?? ''),
            'item_source_hash' => (string) ($row['item_source_hash'] ?? ''),
            'current_media_id' => (string) ($row['media_id'] ?? ''),
            'current_media_file_name' => (string) ($row['media_file_name'] ?? ''),
            'current_media_source_url' => (string) ($row['media_source_url'] ?? ''),
            'current_media_source_hash' => (string) ($row['media_source_hash'] ?? ''),
            'expected_product_url' => (string) ($row['expected_product_url'] ?? ''),
            'expected_source_hash' => (string) ($row['expected_source_hash'] ?? ''),
            'target_source_url' => '',
            'target_source_hash' => '',
            'match_method' => '',
            'donor_item_id' => '',
            'donor_media_id' => '',
            'donor_media_file_name' => '',
            'donor_media_source_url' => '',
            'donor_media_source_hash' => '',
            'donor_image_url' => '',
            'result_media_id' => '',
        ];
    }

    /** @param list<array<string,string>> $rows */
    private function appendOutputRows(string $path, array $rows): void
    {
        if ($rows === []) {
            return;
        }

        $handle = fopen($path, 'ab');

        if ($handle === false) {
            throw new RuntimeException('Unable to append unresolved cross-code rows: '.$path);
        }

        try {
            foreach ($rows as $row) {
                fputcsv($handle, array_map(
                    static fn (string $header): string => (string) ($row[$header] ?? ''),
                    self::OUTPUT_HEADERS,
                ));
            }
        } finally {
            fclose($handle);
        }
    }

    /** @param list<array<string,string>> $rows */
    private function writeCrossCodeCsv(string $path, array $rows): void
    {
        $handle = fopen($path, 'wb');

        if ($handle === false) {
            throw new RuntimeException('Unable to create cross-code review CSV: '.$path);
        }

        try {
            fputcsv($handle, self::OUTPUT_HEADERS);

            foreach ($rows as $row) {
                fputcsv($handle, array_map(
                    static fn (string $header): string => (string) ($row[$header] ?? ''),
                    self::OUTPUT_HEADERS,
                ));
            }
        } finally {
            fclose($handle);
        }
    }

    private function updateSummary(string $outputDirectory, int $crossCodeHashCount, int $appended): void
    {
        $path = $outputDirectory.'/summary.json';

        if (! is_file($path)) {
            return;
        }

        $decoded = json_decode((string) file_get_contents($path), true);

        if (! is_array($decoded)) {
            return;
        }

        $decoded['cross_code_image_hashes'] = $crossCodeHashCount;
        $decoded['cross_code_review_rows'] = $appended;
        $decoded['unsolved'] = (int) ($decoded['unsolved'] ?? 0) + $appended;
        $decoded['already_correct'] = max(0, (int) ($decoded['already_correct'] ?? 0) - $appended);

        file_put_contents(
            $path,
            json_encode($decoded, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR),
        );
    }

    private function validatedLimit(): ?int
    {
        $limit = $this->option('limit');

        if ($limit === null || $limit === '') {
            return null;
        }

        $validated = filter_var($limit, FILTER_VALIDATE_INT);

        if ($validated === false || $validated < 1) {
            throw new InvalidArgumentException('--limit must be a positive integer.');
        }

        return $validated;
    }

    private function outputDirectory(): string
    {
        $configured = trim((string) $this->option('output'));

        if ($configured === '') {
            return storage_path('app/reports/item-image-repair/'.now()->format('Ymd-His'));
        }

        return $this->resolvePath($configured);
    }

    private function createOutputDirectory(string $path): void
    {
        if (! is_dir($path) && ! mkdir($path, 0775, true) && ! is_dir($path)) {
            throw new RuntimeException('Unable to create output directory: '.$path);
        }
    }

    private function resolvePath(string $path): string
    {
        $path = trim($path);

        if ($path === '') {
            throw new InvalidArgumentException('A non-empty path is required.');
        }

        if (Str::startsWith($path, ['/', '\\']) || preg_match('/^[A-Za-z]:[\\\\\/]/', $path) === 1) {
            return rtrim($path, '\\/');
        }

        return rtrim(base_path($path), '\\/');
    }
}
