<?php

return [
    'excel_directory' => env('EXCEL_IMPORT_DIRECTORY', base_path('excel')),

    'canonical_car_groups' => [
        'AUDI VW',
        'BMW',
        'MERCEDES',
        'PSA',
        'OPEL',
        'FIAT',
        'IVECO',
        'RENAULT',
        'JAPAN',
        'KOREA',
        'FORD',
        'JAGUAR',
        'SWEDEN',
        'ROVER&LAND ROVER',
        'RAZNI',
        'USA',
    ],

    'ecotrade_default_group' => 'RAZNI',

    'sheet_aliases' => [
        'VW' => 'AUDI VW',
        'AUDI' => 'AUDI VW',
        'KIA HUNDAY' => 'KOREA',
        'KIA HUNDAY.' => 'KOREA',
        'HYUNDAY' => 'KOREA',
        'HUNDAY' => 'KOREA',
        'CHRAISLER' => 'CHRYSLER',
        'ROVER' => 'ROVER&LAND ROVER',
        'SEVEL' => 'FIAT',
        'РАЗНИ' => 'RAZNI',
        'GM' => 'OPEL',
    ],

    'ecotrade_brand_groups' => [
        'audi' => 'AUDI VW',
        'volkswagen' => 'AUDI VW',
        'vw' => 'AUDI VW',
        'seat' => 'AUDI VW',
        'skoda' => 'AUDI VW',
        'porsche' => 'AUDI VW',
        'bmw' => 'BMW',
        'mini' => 'BMW',
        'mini-cooper' => 'BMW',
        'mercedes' => 'MERCEDES',
        'mercedes-benz' => 'MERCEDES',
        'smart' => 'MERCEDES',
        'peugeot' => 'PSA',
        'citroen' => 'PSA',
        'ds' => 'PSA',
        'opel' => 'OPEL',
        'vauxhall' => 'OPEL',
        'gm' => 'OPEL',
        'fiat' => 'FIAT',
        'alfa-romeo' => 'FIAT',
        'lancia' => 'FIAT',
        'abarth' => 'FIAT',
        'iveco' => 'IVECO',
        'renault' => 'RENAULT',
        'dacia' => 'RENAULT',
        'toyota' => 'JAPAN',
        'lexus' => 'JAPAN',
        'honda' => 'JAPAN',
        'acura' => 'JAPAN',
        'nissan' => 'JAPAN',
        'infiniti' => 'JAPAN',
        'mazda' => 'JAPAN',
        'mitsubishi' => 'JAPAN',
        'subaru' => 'JAPAN',
        'suzuki' => 'JAPAN',
        'isuzu' => 'JAPAN',
        'daihatsu' => 'JAPAN',
        'hino' => 'JAPAN',
        'kia' => 'KOREA',
        'hyundai' => 'KOREA',
        'genesis' => 'KOREA',
        'daewoo' => 'KOREA',
        'ssangyong' => 'KOREA',
        'ford' => 'FORD',
        'jaguar' => 'JAGUAR',
        'volvo' => 'SWEDEN',
        'saab' => 'SWEDEN',
        'rover' => 'ROVER&LAND ROVER',
        'land-rover' => 'ROVER&LAND ROVER',
        'mg' => 'ROVER&LAND ROVER',
        'chevrolet' => 'USA',
        'gmc' => 'USA',
        'cadillac' => 'USA',
        'buick' => 'USA',
        'dodge' => 'USA',
        'jeep' => 'USA',
        'chrysler' => 'USA',
        'ram' => 'USA',
        'lincoln' => 'USA',
        'mercury' => 'USA',
        'pontiac' => 'USA',
        'saturn' => 'USA',
        'tesla' => 'USA',
        'ferrari' => 'RAZNI',
        'walker' => 'RAZNI',
    ],

    'rejected_image_url_fragments' => [
        '/mascots/',
        'mascote_en',
        'placeholder',
        'default-image',
        'default_image',
        'no-image',
        'no_image',
    ],
];
