<?php

declare(strict_types=1);

$root = dirname(__DIR__); $dir = $root . '/storage/app/reports/ecotrade_catalog_audit';
function readCsv(string $path): array { $h=fopen($path,'rb'); $head=fgetcsv($h,0,',','"','\\'); $rows=[]; while(($r=fgetcsv($h,0,',','"','\\'))!==false) if(count($r)===count($head)) $rows[]=array_combine($head,$r); fclose($h); return $rows; }
$items=readCsv($root.'/storage/app/reports/pricing_all_items_audit.csv'); $targets=readCsv($dir.'/targets.csv'); $evidence=readCsv($dir.'/family_evidence.csv'); $ev=[]; foreach($evidence as $r) $ev[$r['family_key']]=$r;
$fx=['EUR'=>1.1481,'€'=>1.1481,'USD'=>1.0,'$'=>1.0]; file_put_contents($dir.'/fx_rates.json',json_encode(['EUR'=>['to_usd'=>$fx['EUR'],'source_url'=>'https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html','observed_at'=>gmdate('c'),'basis'=>'1 EUR = 1.1481 USD']],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));
$targetMap=[]; foreach($targets as $t) $targetMap[$t['family_key']]=$t;
$cmp=[]; $unresolved=[]; $identity=[]; $outliers=[]; $familyStats=[];
function pctBucket(?float $p): string { if($p===null)return 'NOT_COMPARABLE'; $a=abs($p); return $a<=5?'WITHIN_5_PERCENT':($a<=10?'WITHIN_10_PERCENT':($a<=20?'WITHIN_20_PERCENT':($a<=35?'OUTLIER_20_TO_35_PERCENT':'MAJOR_OUTLIER_OVER_35_PERCENT'))); }
foreach($items as $i){ $key=$i['group'].'|'.strtoupper((string)preg_replace('/[^A-Z0-9]+/i','',(string)$i['serial'])); $t=$targetMap[$key]??[]; $e=$ev[$key]??[]; $conf=$e['match_confidence']??'NONE'; $raw=$e['ecotrade_price_raw']??''; $currency=$e['ecotrade_currency']??''; $rate=$fx[$currency]??null; $ecoUsd=($raw!==''&&$rate!==null)?(float)$raw*$rate:null; $local=(float)$i['default_price']; $delta=($ecoUsd!==null)?$local-$ecoUsd:null; $pct=($ecoUsd!==null&&$ecoUsd!=0)?$delta/$ecoUsd*100:null; $warning='NONE'; $detail=strtolower($i['details'].' '.$i['model']); $ptype=strtolower($e['classification']??''); if((str_contains($detail,'dpf')&&$ptype==='catalyst_only')||(!str_contains($detail,'dpf')&&$ptype==='dpf_only')) $warning='PRODUCT_TYPE_MISMATCH'; elseif((string)$i['serial']==='14097610') $warning='SHARED_REFERENCE_ONLY'; elseif((float)($t['local_selected_price_usd_max']??0)-(float)($t['local_selected_price_usd_min']??0)>max(20,(float)($t['local_selected_price_usd_min']??0)*.2)) $warning='LOCAL_VARIANT_PRICE_SPREAD'; if($warning!=='NONE')$identity[$key]=[$key,$warning,$i['group'],$i['serial'],$e['ecotrade_url']??'',$e['details_or_oem_refs']??'']; $bucket=($conf==='EXACT'||$conf==='SUPPORTED')&&$ecoUsd!==null&&$warning!=='PRODUCT_TYPE_MISMATCH' ? pctBucket($pct):'NOT_COMPARABLE'; $row=['item_id'=>$i['item_id'],'group'=>$i['group'],'serial'=>$i['serial'],'model'=>$i['model'],'details'=>$i['details'],'local_weight_kg'=>$i['weight_kg'],'local_pt_ppm'=>$i['pt_ppm'],'local_pd_ppm'=>$i['pd_ppm'],'local_rh_ppm'=>$i['rh_ppm'],'api_visible'=>$i['api_visible'],'mapping_status'=>$i['source_url']!==''?'DIRECT_URL':'NO_DIRECT_URL','review_type'=>$e['classification']??'','local_selected_price_usd'=>$i['default_price'],'local_source_url'=>$i['source_url'],'ecotrade_url'=>$e['ecotrade_url']??'','match_confidence'=>$conf,'product_type'=>$e['product_type']??'','classification'=>$e['classification']??'','ecotrade_price_raw'=>$raw,'ecotrade_currency'=>$currency,'ecotrade_price_usd'=>$ecoUsd===null?'':round($ecoUsd,4),'delta_usd'=>$delta===null?'':round($delta,4),'delta_percent'=>$pct===null?'':round($pct,4),'comparison_bucket'=>$bucket,'identity_warning'=>$warning,'notes'=>$e['notes']??'']; $cmp[]=$row; if($bucket==='NOT_COMPARABLE')$unresolved[]=['family_key'=>$key,'status'=>$conf==='AMBIGUOUS'?'AMBIGUOUS':($raw===''?'NO_PRICE_VISIBLE':'NOT_COMPARABLE'),'reason'=>$warning!=='NONE'?$warning:'Missing exact/supported USD-comparable evidence','ecotrade_url'=>$e['ecotrade_url']??'','observed_at'=>$e['observed_at']??'','notes'=>$e['notes']??'']; if(in_array($bucket,['OUTLIER_20_TO_35_PERCENT','MAJOR_OUTLIER_OVER_35_PERCENT'],true))$outliers[]=$row; }
$cmpPath=$dir.'/item_price_comparison.csv'; $h=fopen($cmpPath,'wb'); fputcsv($h,array_keys($cmp[0]),',','"','\\'); foreach($cmp as $r)fputcsv($h,$r,',','"','\\'); fclose($h);
$uPath=$dir.'/unresolved.csv'; $h=fopen($uPath,'wb'); fputcsv($h,array_keys($unresolved[0]??['family_key','status','reason','ecotrade_url','observed_at','notes']),',','"','\\'); foreach($unresolved as $r)fputcsv($h,$r,',','"','\\'); fclose($h);
$idMd="# IDENTITY_ISSUES\n\nFamilies with product-type conflicts, shared references, or local variant spreads. No records were modified.\n\n"; foreach($identity as $r)$idMd.="- `{$r[0]}` — **{$r[1]}**; local {$r[2]} / {$r[3]}; EcoTrade URL: {$r[4]}; visible details: {$r[5]}\n"; file_put_contents($dir.'/IDENTITY_ISSUES.md',$idMd);
usort($outliers,fn($a,$b)=>abs((float)($b['delta_percent']?:0))<=>abs((float)($a['delta_percent']?:0))); $outMd="# OUTLIERS\n\nCredible exact/supported matches only; EcoTrade EUR values normalized with the recorded ECB rate.\n\n"; foreach(['MAJOR_OUTLIER_OVER_35_PERCENT','OUTLIER_20_TO_35_PERCENT'] as $b){$outMd.="## {$b}\n\n"; foreach(array_filter($outliers,fn($r)=>$r['comparison_bucket']===$b) as $r)$outMd.="- `{$r['item_id']}` {$r['group']} {$r['serial']}: local $".$r['local_selected_price_usd']." vs EcoTrade $".$r['ecotrade_price_usd']."; delta ".$r['delta_percent']."%; {$r['ecotrade_url']}\n";} file_put_contents($dir.'/OUTLIERS.md',$outMd);
$counts=[]; foreach($cmp as $r)$counts[$r['comparison_bucket']]=($counts[$r['comparison_bucket']]??0)+1; $credible=array_values(array_filter($cmp,fn($r)=>$r['comparison_bucket']!=='NOT_COMPARABLE')); $diffs=array_map(fn($r)=>abs((float)$r['delta_percent']),$credible); sort($diffs); $median=$diffs?($diffs[(int)floor((count($diffs)-1)/2)]+$diffs[(int)ceil((count($diffs)-1)/2)])/2:null; $p90=$diffs?$diffs[min(count($diffs)-1,(int)ceil(.9*count($diffs))-1)]:null; $statusCounts=[]; $cp=json_decode((string)file_get_contents($dir.'/checkpoint.json'),true)??[]; foreach(($cp['processed']??[]) as $p)$statusCounts[$p['status']]=($statusCounts[$p['status']]??0)+1;
$summary="# SUMMARY\n\n- Total local items: ".count($items)."\n- Total unique families: ".count($targets)."\n- Exact matches: ".($statusCounts['FOUND_EXACT']??0)."\n- Supported matches: ".($statusCounts['FOUND_SUPPORTED']??0)."\n- Ambiguous: ".($statusCounts['AMBIGUOUS']??0)."\n- Not found: ".($statusCounts['NOT_FOUND']??0)."\n- No visible EcoTrade price: ".($statusCounts['NO_PRICE_VISIBLE']??0)."\n- Comparable item count: ".count($credible)."\n- Within 5%: ".($counts['WITHIN_5_PERCENT']??0)."; within 10%: ".(($counts['WITHIN_5_PERCENT']??0)+($counts['WITHIN_10_PERCENT']??0))."; within 20%: ".(($counts['WITHIN_5_PERCENT']??0)+($counts['WITHIN_10_PERCENT']??0)+($counts['WITHIN_20_PERCENT']??0))."; >20%: ".(($counts['OUTLIER_20_TO_35_PERCENT']??0)+($counts['MAJOR_OUTLIER_OVER_35_PERCENT']??0))."; >35%: ".($counts['MAJOR_OUTLIER_OVER_35_PERCENT']??0)."\n- Median absolute percentage difference: ".($median===null?'n/a':round($median,2).'%')."\n- P90 absolute percentage difference: ".($p90===null?'n/a':round($p90,2).'%')."\n\n## Coverage\n\nEvidence is complete for all target families in the checkpoint, but only exact/supported matches with a visible price and known currency are comparable. EUR evidence was normalized using the ECB rate recorded in `fx_rates.json`; ambiguous, missing-price, identity-warning, and non-USD/unknown-currency rows remain unresolved.\n\n## Largest credible outliers\n\n"; foreach(array_slice($outliers,0,50) as $r)$summary.="- {$r['group']} {$r['serial']} — {$r['delta_percent']}% (`{$r['comparison_bucket']}`)\n"; file_put_contents($dir.'/SUMMARY.md',$summary); echo json_encode(['items'=>count($items),'families'=>count($targets),'comparable'=>count($credible),'unresolved'=>count($unresolved),'outliers'=>count($outliers)],JSON_PRETTY_PRINT).PHP_EOL;
